name: Go CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    # Run the matrix of Go versions that Travis used
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x, latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      # Same command Travis ran
      - name: Run race-test target
        run: make race-test
